### ISSUE TITLE
Qustion about optical flow supervision

### ISSUE THREAD

**Issue by guanjunwu** [tianfr/MonoNeRF#5]
Hi, thanks for your great work!
I carefully read your paper, and I have a question about supervision with optical flow:
As I know, optical flow denotes the transition between near frames, so the static background also owns a offset (related to camera poses), but your proposed velocity fields stand for deformation of the scene(static background should be close to 0). Therefore, volume rendering by velocity field may cause zero-offset because of the low velocity of the background. Does that have bad effect on training?
Meanwhile, I guess the optical flow-based nerf should also split the motion of the camera and the motion of the scene. How can we solve it?
I'm newer to learning the optical flow-based field, looking forward to your reply :)
Best sincerely, 
guanjun

**Comment by tianfr** [comment]
Thank you for your valuable question!

You are right that the optical flow estimated from two adjacent frames contains two parts of flows: flow by camera motions and flow by object movements. Here in the MonoNeRF we just follow the common practice like DynNeRF and NSFF that directly supervise the velocity field with the optical flows and do not consider the camera motion effect on flow. 

For the static parts of the scene, since these parts are rendered by static NeRF, the camera motion contributes nothing to the rendering quality. For the dynamic parts of the scene, due to the small camera movement in the Dynamic Scene Dataset, the camera motion can be considered as a small scale of noise in the supervision signal. In this manner it does not lead to worse performance in the reconstruction tasks.


In addition we have tried manually add different scales of noise to the optical flow maps for supervision. Experimental results show that a small scale of noise (about 5% or less) may somehow can be considered as an augmentation in the training pipeline, which has similar effect of adding Gaussian noise to the input image in the traditional deep learning pipeline. The model could achieve slightly better performance compared to zero-noise optical flow maps.

If you have further concerns or comments, feel free to let me know.
